# Generated by Django 3.0.2 on 2020-06-17 18:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Gielda', '0002_auto_20200617_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gielda_ogloszenie',
            name='data_dodania',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 17, 18, 18, 35, 348769, tzinfo=utc)),
        ),
    ]
