# Generated by Django 3.0.2 on 2020-04-30 13:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tablica', '0002_auto_20200310_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ogloszenie',
            name='powierzchnia_zadruku',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='Powierzchnia zadruku [%]'),
        ),
    ]
